/*------------------------------------------------------------------------------
-- 개체명 : RTMASTER.TBL_MENU_INFO
-- 생성일 : 2016-10-27 오후 2:14:18
-- 최종수정일 : 2016-10-27 오후 2:14:21
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE RTMASTER.TBL_MENU_INFO CASCADE CONSTRAINTS;

CREATE TABLE RTMASTER.TBL_MENU_INFO (
  CORP_CODE   VARCHAR2(2)       NOT NULL,
  MENU_ID       VARCHAR2(30)       NOT NULL,
  MENU_NM       VARCHAR2(100)          NULL,
  UP_MENU_ID    VARCHAR2(30)           NULL,
  SORT_ORDER    NUMBER(5, 1)           NULL,
  MENU_GB       VARCHAR2(30)           NULL,
  CLASS_NM      VARCHAR2(30)           NULL,
  BIGO          VARCHAR2(2000)         NULL,
  USE_YN        VARCHAR2(1)            NULL,
  DEL_YN        VARCHAR2(1)            NULL,
  REG_DTTM      DATE                   NULL,
  REG_IP        VARCHAR2(50)           NULL,
  REG_ID        VARCHAR2(20)           NULL,
  UPD_DTTM      DATE                   NULL,
  UPD_IP        VARCHAR2(50)           NULL,
  UPD_ID        VARCHAR2(20)           NULL
)
TABLESPACE RETAIL_DB
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE (
    INITIAL 64 K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    FREELISTS 1
    FREELIST GROUPS 1
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE RTMASTER.TBL_MENU_INFO IS '메뉴_정보';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.CORP_CODE IS '기업코드';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.MENU_ID IS '메뉴_ID ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.MENU_NM IS '메뉴_명 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.UP_MENU_ID IS '상위_메뉴_ID ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.SORT_ORDER IS '정렬_순서 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.MENU_GB IS '메뉴_구분 [CD0002]';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.CLASS_NM IS '클래스_명 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.BIGO IS '비고 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.USE_YN IS '사용_여부 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.DEL_YN IS '삭제_여부 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.REG_DTTM IS '등록_일시 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.REG_IP IS '등록_IP ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.REG_ID IS '등록_ID ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.UPD_DTTM IS '수정_일시 ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.UPD_IP IS '수정_IP ';

COMMENT ON COLUMN RTMASTER.TBL_MENU_INFO.UPD_ID IS '수정_ID ';

ALTER TABLE RTMASTER.TBL_MENU_INFO ADD
(
    CONSTRAINT TBL_MENU_INFO_PK
    PRIMARY KEY ( CORP_CODE ,MENU_ID )
        USING INDEX
        TABLESPACE RETAIL_DB
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64 K
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            FREELISTS 1
            FREELIST GROUPS 1
        )
);

