/*------------------------------------------------------------------------------
-- 개체명 : RTMASTER.TBL_COMM_CD_INFO
-- 생성일 : 2016-10-27 오후 2:11:09
-- 최종수정일 : 2016-10-27 오후 2:20:47
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE RTMASTER.TBL_COMM_CD_INFO CASCADE CONSTRAINTS;

CREATE TABLE RTMASTER.TBL_COMM_CD_INFO (
  CORP_CODE                       VARCHAR2(2)       NOT NULL,
  CD_CL                       VARCHAR2(30)       NOT NULL,
  CD_ID                       VARCHAR2(30)       NOT NULL,
  MGMT_GB                     VARCHAR2(30)           NULL,
  CD_NM                       VARCHAR2(100)          NULL,
  CD_SHORT_NM                 VARCHAR2(20)           NULL,
  CD_DESCRIPTION              VARCHAR2(2000)         NULL,
  CD_LENG                     NUMBER                 NULL,
  SORT_ORDER                  NUMBER(5, 1)           NULL,
  MGMT_ENTRY_1                VARCHAR2(50)           NULL,
  MGMT_ENTRY_DESCRIPTION_1    VARCHAR2(2000)         NULL,
  MGMT_ENTRY_2                VARCHAR2(50)           NULL,
  MGMT_ENTRY_DESCRIPTION_2    VARCHAR2(2000)         NULL,
  MGMT_ENTRY_3                VARCHAR2(50)           NULL,
  MGMT_ENTRY_DESCRIPTION_3    VARCHAR2(2000)         NULL,
  MGMT_ENTRY_4                VARCHAR2(50)           NULL,
  MGMT_ENTRY_DESCRIPTION_4    VARCHAR2(2000)         NULL,
  MGMT_ENTRY_5                VARCHAR2(50)           NULL,
  MGMT_ENTRY_DESCRIPTION_5    VARCHAR2(2000)         NULL,
  DEL_YN                      CHAR(1)                NULL,
  REG_DTTM                    DATE                   NULL,
  REG_IP                      VARCHAR2(50)           NULL,
  REG_ID                      VARCHAR2(20)           NULL,
  UPD_DTTM                    DATE                   NULL,
  UPD_IP                      VARCHAR2(50)           NULL,
  UPD_ID                      VARCHAR2(20)           NULL
)
TABLESPACE RETAIL_DB
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE (
    INITIAL 64 K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    FREELISTS 1
    FREELIST GROUPS 1
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;


COMMENT ON TABLE RTMASTER.TBL_COMM_CD_INFO IS '공통_코드_정보';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.CORP_CODE IS '기업코드 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_DESCRIPTION_2 IS '관리_항목_설명_2 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_3 IS '관리_항목_3 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_DESCRIPTION_3 IS '관리_항목_설명_3 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_4 IS '관리_항목_4 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_DESCRIPTION_4 IS '관리_항목_설명_4 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_5 IS '관리_항목_5 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_DESCRIPTION_5 IS '관리_항목_설명_5 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.DEL_YN IS '삭제_여부 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.REG_DTTM IS '등록_일시 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.REG_IP IS '등록_IP ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.REG_ID IS '등록_ID ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.UPD_DTTM IS '수정_일시 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.UPD_IP IS '수정_IP ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.UPD_ID IS '수정_ID ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.CD_CL IS '코드_분류 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.CD_ID IS '코드_ID ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_GB IS '관리_구분 [CD0001]';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.CD_NM IS '코드_명 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.CD_SHORT_NM IS '코드_단축_명 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.CD_DESCRIPTION IS '코드_설명 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.CD_LENG IS '코드_길이 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.SORT_ORDER IS '정렬_순서 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_1 IS '관리_항목_1 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_DESCRIPTION_1 IS '관리_항목_설명_1 ';

COMMENT ON COLUMN RTMASTER.TBL_COMM_CD_INFO.MGMT_ENTRY_2 IS '관리_항목_2 ';

ALTER TABLE RTMASTER.TBL_COMM_CD_INFO ADD
(
    PRIMARY KEY ( CORP_CODE, CD_CL, CD_ID )
        USING INDEX
        TABLESPACE RETAIL_DB
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64 K
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            FREELISTS 1
            FREELIST GROUPS 1
        )
);

